%YAML:1.0
---
frame_width: 640
frame_height: 480
blue_channel_gain: 100
green_channel_gain: 119
red_channel_gain: 142
saturation: 95
contrast: 109
gamma: 72
sharpness: 0
auto_exp_target_brightness: 120
exposure_time: 8190
analog_gain: 1
exposure_mode: 0
wb_mode: 0
