%YAML:1.0
---
frame_width: 640
frame_height: 480
blue_channel_gain: 100
green_channel_gain: 134
red_channel_gain: 172
saturation: 133
contrast: 131
gamma: 91
sharpness: 40
auto_exp_target_brightness: 120
exposure_time: 8190
analog_gain: 0
exposure_mode: 0
wb_mode: 0
